### ISSUE TITLE
Stuck after entering main loop

### ISSUE THREAD

**Issue by emjotde** [nyu-dl/dl4mt-multi#2]
Hi,
I am trying to train an 2-Encoder/1-Decoder model, but the training process seems to get stuck right before the first iteration. 

The computation graphs seems to be built (allocates ca. 3.5GB on gpu0), the main loop of blocks is being entered:

```
-------------------------------------------------------------------------------
BEFORE FIRST EPOCH
-------------------------------------------------------------------------------
Training status:
         batch_interrupt_received: False
         epoch_interrupt_received: False
         epoch_started: True
         epochs_done: 0
         iterations_done: 0
         received_first_batch: False
         resumed_from: None
         training_started: True
Log records from the iteration 0:
         time_initialization: 3.81469726562e-06

```

but then nothing happens. GPU displays 0% load, waited for 1h, also tested with very small training files. The main CPU process is running at 100%. Has anybody seen behaviour like that? Any suggestions?

Thanks,
Marcin

**Comment by orhanf** [comment]
Hi @emjotde , i remember getting stuck in the very same place and iirc this was related with the data-iterators. 
Have you checked the sizes of the files that you are iterating over? One of your input files might be empty/corrupted.

**Comment by emjotde** [comment]
Hm, the files look alright and have the same number of lines. Used them successfully before for normal nmt training. Anyways, thanks for the tip with the iterator, I will dig around.

**Comment by emjotde** [comment]
The suggestion with the streams was a good one, however, it seems this is a bug in the _too_long predicate from "mcg/streams.py" or in pickable_itertools. The following code reproduces the bug for me:

```
from fuel.datasets import TextFile
from fuel.transformers import (Merge, Filter)

class _too_long(object):
    def __init__(self, seq_len=50):
        self.seq_len = seq_len

    def __call__(self, sentence_pair):
        return all([len(sentence) <= self.seq_len
                    for sentence in sentence_pair]) 

if __name__ == "__main__":
    dic = { "<S>": 0, "</S>":0, "<UNK>": 1 }

    with open("sometext.txt", "w") as f:
       f.write("This is a test\n")
       f.write("This is another test\n")

    src_data = TextFile(files=['sometext.txt'],
                        dictionary=dic)

    trg_data = TextFile(files=['sometext.txt'],
                        dictionary=dic)


    stream = Merge([src_data.get_example_stream(),
                    trg_data.get_example_stream()],
                    ('source', 'target'))

    stream = Filter(stream, predicate=_too_long(40))

    for data in stream.get_epoch_iterator():
         print(data)
```

which results in the following error:

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    for data in stream.get_epoch_iterator():
  File "/usr/lib/python2.7/dist-packages/six.py", line 558, in next
    return type(self).__next__(self)
  File "build/bdist.linux-x86_64/egg/picklable_itertools/filter.py", line 33, in __next__
  File "build/bdist.linux-x86_64/egg/picklable_itertools/filter.py", line 29, in _keep
TypeError: __call__() takes exactly 2 arguments (3 given)
```

BTW. this sends your tool into an exception loop, hence the lock.

**Comment by emjotde** [comment]
Adding a third function parameter to the predicate actually fixes things and it works now. The value of `dummy` seems to be an empty dictionary. 

```
    def __call__(self, sentence_pair, dummy):
        return all([len(sentence) <= self.seq_len
                    for sentence in sentence_pair])
```

**Comment by orhanf** [comment]
Are you using the latest version of Fuel ?

**Comment by orhanf** [comment]
@emjotde would you mind making a pr with this ?
